@extends('layouts.invoiceLayout')
@section('content')
    <div class="row">
        <div class="col-sm-6"><strong>Generated At:</strong> {{$inv->created_at}}</div>
        <div class="col-sm-6 text-sm-right"> <strong>Invoice No: </strong>Inv-{{$inv->id}}</div>

    </div>
    <hr>
    <div class="row">
        <div class="col-sm-6 text-sm-right order-sm-1"> <strong>Generated By:</strong>
            <address>
                {{$inv->seller}}<br />
                {{config('app.name')}}  <br/>
                Rabeya Latif Market<br />
                {{Auth::guard('admin')->user()->cellnum}}
            </address>
        </div>
        <div class="col-sm-6 order-sm-0"> <strong>Invoiced To:</strong>
            <address>
                {{$inv->customername}}<br />
                {{$inv->cellnum}}<br />
            </address>
        </div>
    </div>


    <table  class="table table-striped">
        <thead>
        <tr>
            <th scope="col"><div align="left">Item Name</div></th>
            <th scope="col"><div align="center">Category</div></th>

            <th scope="col"><div align="center">Unit Price</div></th>
            <th scope="col"><div align="center">Quantity</div></th>
            <th scope="col"><div align="center">Amount</div></th>

            <!--<th scope="col"><div align="center">Action</div></th>-->
        </tr>
        </thead>
        <tbody>
        @foreach($invS as $item)
            <tr >

                <td scope="row"><strong>{{$item->productName}}</strong></td>
                <td><div align="center">{{$item->category}}</div></td>
                <td><div align="center">{{$item->price}}</div></td>

                <td><div align="center">{{$item->quantity}}</div></td>
                <td><div align="center">{{$item->price * $item->quantity}}</div></td>
            </tr>
        @endforeach


        @if($inv->discount>0)
            <tr>
                <td colspan="4" class="bg-light-2 text-right"><strong>Sub Total:</strong></td>
                <td class="bg-light-2 text-center">{{$inv->subtotal}}</td>
            </tr>
        <tr>
            <td colspan="4" class="bg-light-2 text-right"><strong>Discount:</strong></td>
            <td class="bg-light-2 text-center">{{$inv->discount}}</td>
        </tr>

        <tr>
            <td colspan="4" class="bg-light-2 text-right"><strong>Total:</strong></td>
            <td class="bg-light-2 text-center">{{$inv->total}}</td>
        </tr>
            @else
            <tr>
                <td colspan="4" class="bg-light-2 text-right"><strong>Total:</strong></td>
                <td class="bg-light-2 text-center">{{$inv->subtotal}}</td>
            </tr>
        @endif
        <tr>
            <td colspan="4" class="bg-light-2 text-right"><strong>Tax:</strong></td>
            <td class="bg-light-2 text-center">{{$inv->tax}}</td>
        </tr>
        <tr>
            <td colspan="4" class="bg-light-2 text-right"><strong>Payable:</strong></td>
            <td class="bg-light-2 text-center">{{$inv->total+$inv->tax}}</td>
        </tr>

        </tbody>
    </table>
    @endsection
