@extends('layouts.invoiceLayout')
@section('content')
    <div class="row">
        <div class="col-sm-6"><strong>Generated At:</strong> {{date("d.m.Y")}} | {{date("h:i:sa")}}</div>
        <div class="col-sm-6 text-sm-right"> <strong>Invoice No:</strong> Inv-{{$invCount->count()}}</div>

    </div>
    <hr>
    <div class="row">
        <div class="col-sm-6 text-sm-right order-sm-1"> <strong>Generated By:</strong>
            <address>
                {{Auth::guard('admin')->user()->firstname}}<br />
                {{config('app.name')}}  <br/>
                Rabeya Latif Market<br />
                {{Auth::guard('admin')->user()->cellnum}}
            </address>
        </div>
        <div class="col-sm-6 order-sm-0"> <strong>Invoiced To:</strong>
            <address>
                {{Session::get('customerName')}}<br />
                {{Session::get('customerCellnum')}}<br />
            </address>
        </div>
    </div>


    <table  class="table table-striped">
        <thead>
        <tr>
            <th scope="col"><div align="left">Item Name</div></th>
            <th scope="col"><div align="center">Category</div></th>

            <th scope="col"><div align="center">Unit Price</div></th>
            <th scope="col"><div align="center">Quantity</div></th>
            <th scope="col"><div align="center">Amount</div></th>

            <!--<th scope="col"><div align="center">Action</div></th>-->
        </tr>
        </thead>
        <tbody>
        @foreach($cart->getContent() as $item)
            <tr >

                <td scope="row"><strong>{{$item->name}}</strong></td>
                <td><div align="center">{{$item->associatedModel->category}}</div></td>
                <td><div align="center">{{$item->price}}</div></td>

                <td><div align="center">{{$item->quantity}}</div></td>
                <td><div align="center">{{$item->price * $item->quantity}}</div></td>
            </tr>
        @endforeach


        @if(floor($cart->getSubTotal())>floor($cart->getTotal()))
            <tr>
                <td colspan="4" class="bg-light-2 text-right"><strong>Sub Total:</strong></td>
                <td class="bg-light-2 text-center">{{$cart->getSubTotal()}}</td>
            </tr>
            <tr>
                <td colspan="4" class="bg-light-2 text-right"><strong>Discount:</strong></td>
                <td class="bg-light-2 text-center">{{$cart->getSubTotal()-$cart->getTotal()}}</td>
            </tr>

            <tr>
                <td colspan="4" class="bg-light-2 text-right"><strong>Total:</strong></td>
                <td id="totalID" class="bg-light-2 text-center">{{floor($cart->getTotal())}}</td>
            </tr>
            @else
            <tr>
                <td colspan="4" class="bg-light-2 text-right"><strong>Total:</strong></td>
                <td id="totalID" class="bg-light-2 text-center">{{$cart->getSubTotal()}}</td>
            </tr>
            @endif
        <tr>
            <td colspan="3" class="bg-light-2 text-right">Tax:
                <input onchange="onChangeTax()" style="width: 50px" type="number"
                       placeholder=""
                       value="0"
                       id="taxID">%
                <input id="saleIdentifier" value="{{Session::get('saleIdentifier')}}" hidden>

            </td>
            <td  class="bg-light-2 text-right"><strong>Tax:</strong></td>
            <td id="taxField" class="bg-light-2 text-center">0</td>
        </tr>
        <tr>
            <td colspan="4" class="bg-light-2 text-right"><strong>Payable:</strong></td>
            <td id="payableID" class="bg-light-2 text-center">{{floor($cart->getTotal())}}</td>
        </tr>

        </tbody>
    </table>
    @endsection

