@extends('layouts.statementLayout')
@section('statementName')
    Sales And Stock
    @endsection
@section('content')
    <div class="row">
        <div class="col-sm-6"><strong>Generated At:</strong> {{date("d.m.Y")}} | {{date("h:i:sa")}}</div>

    </div>
    <hr>
    <div class="row">
        <div class="col-sm-6 text-sm-right order-sm-1"> <strong>Statement Of:</strong>
            <address>
                {{config('app.name')}}  <br/>
                Rabeya Latif Market<br />

            </address>
        </div>
        <div class="col-sm-6 order-sm-0"> <strong>Generated By:</strong>
            <address>
                {{Auth::guard('admin')->user()->firstname}}<br />
                {{Auth::guard('admin')->user()->cellnum}}<br />
            </address>
        </div>
    </div>


    <table  class="table table-striped">
        <thead>
        <tr>
            <th scope="col"><div align="left">Date</div></th>
            <th scope="col"><div align="center">Name</div></th>
            <th scope="col"><div align="center">Quantity</div></th>
            <th scope="col"><div align="center">Price</div></th>
            <th scope="col"><div align="center">Mark</div></th>
        </tr>
        </thead>
        <tbody>
        @foreach($inv as $item)
            <tr >

                <td scope="row"><strong>{{$item->date}}</strong></td>
                <td><div align="center">{{$item->name}}</div></td>

                <td><div align="center">{{$item->quantity}}</div></td>

                @if($item->tag=="Sales")
                    <td><div align="center">{{$item->price}}</div></td>
                    <td><div style="color: #06BAF1;" align="center"><b>{{$item->tag}}</b></div></td>
                @elseif($item->tag=="Stock")
                    <td><div align="center"><b>{{$item->price}}</b></div></td>
                    <td><div style="color: #883999;" align="center"><b>{{$item->tag}}</b></div></td>
                @endif

            </tr>
        @endforeach



        </tbody>
    </table>

    @endsection
